### ISSUE TITLE
short version of https://covid19-rest.herokuapp.com/api/jhu/v1/all

### ISSUE THREAD

**Issue by timholz** [apfeuti/covid19-rest#2]
Is it possible to provide a short version of the above mentioned target?
Key «records» is huge and provides a lot of info that is not very relevant for Switzerland.
Key «totals» is sufficient enough. Thanks for the api.

**Comment by apfeuti** [comment]
Yes, I was also thinking about that. I suppose to add an additional optional-parameter:
?skipRecords=true
I will do that later on this week.

If you are interested in figures about Switzerland only, then I recommend to use the api/openzh/ which is more detailed for Switzerland.

Or you could use also: api/jhu/v1/country/che  then you have only totals for Switzerland and "records" is much smaller.

**Comment by timholz** [comment]
An additional parameter would be perfect.
Thanks for the hint, but i am already pulling the above mentioned resources for switerzland.
All works flawlessly.

**Comment by apfeuti** [comment]
skipRecords - parameter is added and deployed for api/openzh and api/jhu. See README "Query-Parameters"

**Comment by timholz** [comment]
Thank you.
