### ISSUE TITLE
combining url parameters: all?skipRecords=true?date=' . $date;

### ISSUE THREAD

**Issue by timholz** [apfeuti/covid19-rest#4]
In order to visualize the development with a diagramm, i use loop calls:
`$date = $array[$i];
$openZH_url = 'https://covid19-rest.herokuapp.com/api/openzh/v1/all/?date=' . $date;`
For a range of four weeks this is rather time consuming since also records are delivered.
Is it possible to combine parameters like so:
`$openZH_url = 'https://covid19-rest.herokuapp.com/api/openzh/v1/all?skipRecords=true?date=' . $date;`?

**Comment by apfeuti** [comment]
Yes, this is possible. But you have to replace the second ? with an &

?skipRecords=true&date=2020-04-18

This is 'normal' URL behavior. You can combine all parameters in any order.
First ? then all remaining with &

Do you have a link to your project? Would be interested.

**Comment by timholz** [comment]
Thanks again for the hint. It works, but it’s no big performance improvement.
I guess i’ll have to find another method with long range caching and short term fetching.

Sorry, but i am rather reluctant in providing a project link, since this project happens for learning purposes in a protected area. And anyway it’s no big deal. But thanks for your interest and help.
