### ISSUE TITLE
add "latest" as a possible date

### ISSUE THREAD

**Issue by rsalzer** [apfeuti/covid19-rest#9]
Feature request:
Add a "latest" call for the openzh-api to show the latest entries for all cantons (and respective totals).
I noticed that the death-totals shrink sometimes when certain cantons did not deliver data yet.

Or: Really forward propagate "old" entries ... so if I add ?date=2020-09-21 it also shows VD with 2020-09-16 (its latest entry...)

**Comment by apfeuti** [comment]
The fields ending with _fwd should forward the latest values. I will investigate why it not always works at beginning of october.

**Comment by apfeuti** [comment]
For missing days (a day, for which a canton does not yet report any data) an artifical row is inserted. The values from the last known day are forwarded to this row.

Example: (AG has not yet reported data for 2020-10-19) Remark: this works also for any missing day in the timeline, eg. UR 2020-08-15 and 2020-08-16, where data are forwarded from 2020-08-14.

{
      "date": "2020-10-19",
      "abbreviation_canton_and_fl": "AG",
      "ncumul_tested_fwd": 0,
      "ncumul_conf_fwd": 3846,
      "ncumul_hosp_fwd": 26,
      "ncumul_ICU_fwd": 2,
      "ncumul_vent_fwd": 1,
      "current_hosp_fwd": 26,
      "current_icu_fwd": 2,
      "current_vent_fwd": 1,
      "ncumul_released_fwd": 2675,
      "ncumul_deceased_fwd": 58
    },

**Comment by rsalzer** [comment]
Could you please set the date of the entries where you forwarded the value from yesterday to the actual date of the entry? That way it would be obvious which ones have recent data and which ones got "forwarded" ones.

**Comment by apfeuti** [comment]
Sorry, I don't understand what you mean.
Below is an example. There were no data for 2020-10-19, so the values were forwarded from 2020-10-18. In the "artifical row" for 2020-10-19 you have only value-fields with *_fwd.

{
      "date": "2020-10-18",
      "time": "08:00",
      "abbreviation_canton_and_fl": "AG",
      "ncumul_tested": "",
      "ncumul_conf": 3846,
      "new_hosp": "",
      "current_hosp": "",
      "current_icu": "",
      "current_vent": "",
      "ncumul_released": 2675,
      "ncumul_deceased": 58,
      "source": "https://www.ag.ch/media/kanton_aargau/themen_1/coronavirus_1/daten_excel/Covid-19-Daten_Kanton_Aargau.xlsx",
      "current_isolated": "",
      "current_quarantined": "",
      "current_quarantined_riskareatravel": "",
      "current_quarantined_total": "",
      "ncumul_tested_fwd": 0,
      "ncumul_conf_fwd": 3846,
      "ncumul_hosp": "",
      "ncumul_ICU": "",
      "ncumul_vent": "",
      "ncumul_hosp_fwd": 26,
      "ncumul_ICU_fwd": 2,
      "ncumul_vent_fwd": 1,
      "current_hosp_fwd": 26,
      "current_icu_fwd": 2,
      "current_vent_fwd": 1,
      "ncumul_released_fwd": 2675,
      "ncumul_deceased_fwd": 58
    },
    {
      "date": "2020-10-19",
      "abbreviation_canton_and_fl": "AG",
      "ncumul_tested_fwd": 0,
      "ncumul_conf_fwd": 3846,
      "ncumul_hosp_fwd": 26,
      "ncumul_ICU_fwd": 2,
      "ncumul_vent_fwd": 1,
      "current_hosp_fwd": 26,
      "current_icu_fwd": 2,
      "current_vent_fwd": 1,
      "ncumul_released_fwd": 2675,
      "ncumul_deceased_fwd": 58
    },

Please make a concrete example, how the data of 2020-10-19 should look like.

**Comment by rsalzer** [comment]
Sorry, my fault. I missed that ncumul_conf signifies data from today. Perfect now! Thanks.
